use_frameworks!

target 'Agent_Example' do
  pod 'Agent', :path => '../'
  pod 'AlgoliaSearch-Client-Swift', '~> 5.0'
  pod 'Result'

  target 'Agent_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  pod 'FBSnapshotTestCase' , '~> 2.1.4'
  pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
